"""add start and end date for the task

Revision ID: bb9f86df333c
Revises: 3a36be54f4f1
Create Date: 2025-04-02 00:32:41.005724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bb9f86df333c"
down_revision: Union[str, None] = "3a36be54f4f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("start_date", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("end_date", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")

    # ### end Alembic commands ###
